# -*- coding: utf-8 -*-
"""jee_rank_predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOz26sz2CiOv0Eq7yyGKUE1azX4B3l2d
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# !wget https://github.com/Plenue/Jee-Rank-Predictor/blob/master/Dataset2014.csv

import pandas as pd

# data = pd.read_csv("/content/Dataset2014.csv")
data = pd.read_csv("/content/Dataset2014.csv")

data.head()

a = data.IN
lst = []
for i in a:
  l = []
  l.append(i)
  lst.append(l)
lst
x = np.array(lst)

import matplotlib.pyplot as plt

y = data.iloc[:,data.columns == "OUT"].values
plt.xlabel("marks")
plt.ylabel("ranks")
plt.scatter(x,y,color = 'k')
plt.show()

poly = PolynomialFeatures(degree=4)
x_p = poly.fit_transform(x)

from sklearn.linear_model import LinearRegression
import numpy as np
model = LinearRegression()

model.fit(x_p, y)

yfit = model.predict(x_p)

plt.xlabel("marks")
plt.ylabel("rank")
plt.scatter(x, y, color = 'k')
plt.plot(x, yfit,color='blue')
plt.show()

res = model.predict(poly.fit_transform([[130]]))
r = res[0][0] 
r = round(r,0)
r